name: Nightly

on:
  push:
    paths:
      - "**.zig"
      - "dl_sdl2.ps1"
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.2063+804cee3b9
      - run: |
            git config --global core.autocrlf false
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
            sudo apt update
            sudo apt install libgtk-3-dev libsdl2-dev
      - name: prepare-windows
        if: runner.os == 'Windows'
        run: |
            .\dl_sdl2.ps1
      - name: prepare-macos
        if: runner.os == 'macOS'
        run: |
            brew install sdl2
      - name: build 
        run: zig build -Doptimize=ReleaseSafe -Dcpu=baseline
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: zba-${{matrix.os}}
          path: zig-out

  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.2063+804cee3b9
      - run: zig fmt --check {src,lib}/**/*.zig build.zig build.zig.zon
